GET http://localhost:3333/customers

###

GET http://localhost:3333/statement
cpf: 289

###

GET http://localhost:3333/statement/date?date=2025-02-23
cpf: 289
###

POST http://localhost:3333/account
Content-Type: application/json

{
    "cpf": "99999999",
    "name": "Orotio"
}

###

POST http://localhost:3333/deposit
cpf: 289
Content-Type: application/json

{
    "description": "Recheada",
    "amount": 400.00
}
###

POST http://localhost:3333/withdraw
cpf: 289
Content-Type: application/json

{
    "amount": 400.00
}
###

PUT http://localhost:3333/account/
cpf: 289
Content-Type: application/json

{
    "name": "Batman"
}


###

DELETE http://localhost:3333/account/
cpf: 1
