GET http://localhost:3333/customers

###

GET http://localhost:3333/statement
cpf: 21

###

GET http://localhost:3333/statement/date?date=2025-02-23
cpf: 21
###

POST http://localhost:3333/account
Content-Type: application/json

{
    "cpf": "12",
    "name": "bra444fsge22ifefwn rot"
}

###

POST http://localhost:3333/deposit
cpf: 12
Content-Type: application/json

{
    "description": "Recheada",
    "amount": 400.00
}
###

POST http://localhost:3333/withdraw
cpf: 21
Content-Type: application/json

{
    "amount": 400.00
}
###

PUT http://localhost:3333/account/
cpf: 21
Content-Type: application/json

{
    "name": "Batman"
}


###

DELETE http://localhost:3333/account/
cpf: 12
